### ISSUE TITLE
[Feature Req] Text Buffer Size and Unlimited Lifetime

### ISSUE THREAD

**Issue by MAGNAT2645** [DosMike/tf2hudmsg#1]
1. Game uses [`MAX_TRAINING_MSG_LENGTH`](https://github.com/lua9520/source-engine-2018-hl2_src/blob/3bf9df6b2785fa6d951086978a3e66f49427166a/game/client/tf/tf_hud_annotationspanel.cpp#L626) as buffer max length which is equal to [`512`](https://github.com/lua9520/source-engine-2018-hl2_src/blob/3bf9df6b2785fa6d951086978a3e66f49427166a/game/client/tf/tf_hud_training.h#L25).
So i recommend to increase `MAX_ANNOTATION_LENGTH` to `512` as well.
2. Game seems [to allow setting lifetime for annotations to negative value](https://github.com/lua9520/source-engine-2018-hl2_src/blob/3bf9df6b2785fa6d951086978a3e66f49427166a/game/client/tf/tf_hud_annotationspanel.cpp#L597-L600) to avoid their disappearance.
Also negative lifetime seems to have different appearance animation as described [here](https://developer.valvesoftware.com/wiki/Training_annotation#Keyvalues) (Same fade in animation is used in training mode).
I thought this would be good addition to this library but i guess this will break things like `fire & forget` and estimated time out.
3. **Optional**: I also suggest you to add a special constant which will define invalid annotations since SourcePawn initializes variables with zero and for example if you have an array of `CursorAnnotation`s for each player then each array element will point to the same one annotation with index `0` unless you set it to `-1` manually. In my case i have to define `INVALID_ANNOTATION` in every plugin where i use CursorAnnotations (storing them in array for each player) so when plugin starts or client connects i just set current annotation for that client to `INVALID_ANNOTATION` and then later check it with `IsValid` (creating a new one if it isn't valid).

`#define INVALID_ANNOTATION view_as<CursorAnnotation>(-1)`
or
```sourcepawn
enum CursorAnnotation
{
    INVALID_ANNOTATION = -1
};
```

**Comment by DosMike** [comment]
Hi, thanks for bringing this to my attention. Hope the new release addesses your issues.

**Comment by MAGNAT2645** [comment]
Thanks, but smx file from releases was compiled using SourceMod 1.12+ so i had to recompile it for 1.11 after getting this error:
`Failed to load plugin "tf2hudmsg.smx": Newer SourceMod required (1.12.0.7041 or higher).`
