### ISSUE TITLE
Annotations stopped showing after last update

### ISSUE THREAD

**Issue by MAGNAT2645** [DosMike/tf2hudmsg#2]
I use CursorAnnotations in a few plugins but after updating to the latest version they stopped showing.
I added some checks to see if they're even valid (`IsValid`) and they are.
I set lifetime for example to `3.0`, `SetText` to something (after doing `EscapeVGUILocalization`) and `VisibilityBitmask` to `1 << client` so only i can see them.
No errors in the logs (there were a few about closed annotations but i fixed them), they just dont appear.
I guess this is due to using `visibilityPartition` only in `SetVisibilityFor` method so if you want to use `SetVisibilityAll` or `VisibilityBitmask` these partitions aren't being updated (staying as zeros `WillBeVisible` returns `false` and that stops the whole `Send` thingy).

You should also mention in the docs that `ParentEntity` can be used only with entity indices and not their references.

**Comment by MAGNAT2645** [comment]
At least `WillBeVisible` only should be checked if `MaxClients > 32`.

**Comment by DosMike** [comment]
OnMapEnd autocloses the annotations now and marks them as undeployed. Sorry if I forgot any other other logic change there.

The visibility logic seems to be kinda broken yea... I switched to extendend playerlimit at some point and didn't switch back. ``visibilityPartition[0]|visibilityPartition[1]|visibilityPartition[2]|visibilityPartition[3]`` was intended to be identical to the visibility bitmask, but i think I'll just remove that and use the 4 ints only. Reconstruction to a bitmask for 32-player servers is simple.

For ParentEntity, I think the range check was just incorrect. It should support EntRefs. I think the sign bit used to be set for entrefs, but that might no longer be the case... I fear the 4096 entity limit check might just break with a future update, based on what ficool2 is hinting at in the SM discord, but we'll see.

I'll test this and push another release (this time compiled with SM 1.11 :D)

**Comment by DosMike** [comment]
Hope it works now

**Comment by MAGNAT2645** [comment]
Thanks, i'll test it and close issue if it's fixed.
Also `SetPosition` doesn't work for me as an offset to the parent entity, if i set parent entity, annotation just keeps to teleport to the entity, to the same origin (even if i use different vectors).
I guess this code is used to reposition an annotation but as i see only Z axis is used as an offset.
Still, setting Z axis to any arbitrary value doesn't seem to change annotation position.
```cpp
	// Reposition the callout based on our target's position
	Vector vecTarget = m_Location;
	if ( m_FollowEntity.Get() )
	{
		vecTarget = m_FollowEntity->GetAbsOrigin();
		if ( m_FollowEntity->CollisionProp() )
		{
			vecTarget.z += m_FollowEntity->CollisionProp()->OBBSize().z;
		}
	}
```

**Comment by DosMike** [comment]
The code you show, means that, as soon as it follows an entity, it will ignore the offset you give it, and, if it has a collision box, put it above the entity to follow. No value from the vector is used in that case. Kind of sad.
If you want you can spawn an info_target, parent that relative to the actual entity and set the annotation to follow that.

**Comment by DosMike** [comment]
TBH i dont know why i commented that this would work as offset, the event parameter is literally called ``worldPos``

**Comment by MAGNAT2645** [comment]
`info_target` wont help because i use `GetClientAimTarget` to get an entity the player is looking at and then show annotation above it.
One thing that is possible is to somehow store child `info_target` to the actual entity so when player is looking at the entity i can get its child `info_target` and show annotation on it. But this is tricky and in some cases would cause bugs because i do additional checks like `if ( EntRefToEntIndex( annotation.ParentEntity ) == iEntity )` to make sure that player is `+use`ing same entity as the one in the annotation.

**Comment by MAGNAT2645** [comment]
I forgor about this issue. Closing it.
Again, thanks for the fix.
